const DIMENSIONS=["statement_readiness","context_readiness","notation_readiness","dependency_readiness"];
const LIST_FIELDS=[["existing_theorem_candidates","Existing theorem candidates"],["constructive_path","Constructive path"],["blockers","Blockers"]];
const RUBRIC=[["source_fidelity","Source fidelity"],["actionability","Actionability"],["library_alignment","Library alignment"],["blocker_specificity","Blocker specificity"],["path_clarity","Path clarity"]];
let currentReport=null,currentUnit=null,correctedState=null;
const $=id=>document.getElementById(id);
const apiBase=()=>$("api-base").value.replace(/\/$/,"");
const linesToList=v=>v.split("\n").map(s=>s.trim()).filter(Boolean);
const listToLines=v=>(v||[]).join("\n");
const clone=o=>JSON.parse(JSON.stringify(o));
const setText=(el,text)=>{el.textContent=text==null?"":String(text);};
const appendPre=(container,text)=>{const pre=document.createElement("pre");setText(pre,text);container.appendChild(pre);return pre;};
const appendDl=(container,entries,className)=>{const dl=document.createElement("dl");if(className)dl.className=className;for(const[term,def]of entries){const dt=document.createElement("dt");setText(dt,term);const dd=document.createElement("dd");setText(dd,def);dl.appendChild(dt);dl.appendChild(dd);}container.appendChild(dl);return dl;};
async function fetchJson(path){const r=await fetch(path);if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json();}
function renderSource(unit){const container=$("source-spans");container.replaceChildren();appendDl(container,[["Unit",unit.unit_id],["Statement span",unit.statement_span?`[${unit.statement_span.start}, ${unit.statement_span.end})`:"(none)"],["Proof span",unit.proof_span?`[${unit.proof_span.start}, ${unit.proof_span.end})`:"(none)"],["Statement",unit.statement],["Proof",unit.proof||"(none)"]],"source-dl");}
function renderDimensions(){const grid=$("dimension-grid");grid.replaceChildren();for(const n of DIMENSIONS){const c=currentReport[n],e=correctedState[n];const article=document.createElement("article");article.className="dimension-card";article.dataset.dimension=n;const h3=document.createElement("h3");setText(h3,n);article.appendChild(h3);const sideBySide=document.createElement("div");sideBySide.className="side-by-side";const candidateDiv=document.createElement("div");const h4Candidate=document.createElement("h4");setText(h4Candidate,"Candidate");candidateDiv.appendChild(h4Candidate);const pStatus=document.createElement("p");setText(pStatus,c.status);candidateDiv.appendChild(pStatus);appendPre(candidateDiv,listToLines(c.recovered));appendPre(candidateDiv,listToLines(c.unresolved));sideBySide.appendChild(candidateDiv);const correctedDiv=document.createElement("div");const h4Corrected=document.createElement("h4");setText(h4Corrected,"Corrected");correctedDiv.appendChild(h4Corrected);const statusInput=document.createElement("input");statusInput.className="dim-status";statusInput.value=e.status;correctedDiv.appendChild(statusInput);const recoveredTextarea=document.createElement("textarea");recoveredTextarea.className="dim-recovered";recoveredTextarea.value=listToLines(e.recovered);correctedDiv.appendChild(recoveredTextarea);const unresolvedTextarea=document.createElement("textarea");unresolvedTextarea.className="dim-unresolved";unresolvedTextarea.value=listToLines(e.unresolved);correctedDiv.appendChild(unresolvedTextarea);const notesTextarea=document.createElement("textarea");notesTextarea.className="dim-notes";notesTextarea.value=e.notes||"";correctedDiv.appendChild(notesTextarea);sideBySide.appendChild(correctedDiv);article.appendChild(sideBySide);grid.appendChild(article);}}
function renderLists(){const container=$("list-fields");container.replaceChildren();for(const[k,l]of LIST_FIELDS){const div=document.createElement("div");div.className="list-field";div.dataset.field=k;const h3=document.createElement("h3");setText(h3,l);div.appendChild(h3);const sideBySide=document.createElement("div");sideBySide.className="side-by-side";appendPre(sideBySide,listToLines(currentReport[k]));const textarea=document.createElement("textarea");textarea.className="corrected-list";textarea.value=listToLines(correctedState[k]);sideBySide.appendChild(textarea);div.appendChild(sideBySide);container.appendChild(div);}$("next-action").value=correctedState.recommended_next_action;}
function renderRubric(){const container=$("rubric-scores");container.replaceChildren();for(const[k,l]of RUBRIC){const label=document.createElement("label");label.className="rubric-row";const span=document.createElement("span");setText(span,l);label.appendChild(span);const input=document.createElement("input");input.type="number";input.min="1";input.max="5";input.dataset.rubric=k;input.value="4";label.appendChild(input);container.appendChild(label);}}
function readCorrected(){const r=clone(correctedState);for(const n of DIMENSIONS){const card=$("dimension-grid").querySelector(`[data-dimension="${n}"]`);r[n]={status:card.querySelector(".dim-status").value.trim(),recovered:linesToList(card.querySelector(".dim-recovered").value),unresolved:linesToList(card.querySelector(".dim-unresolved").value),notes:card.querySelector(".dim-notes").value.trim()||null};}
for(const [k] of LIST_FIELDS){r[k]=linesToList($("list-fields").querySelector(`[data-field="${k}"] .corrected-list`).value);}r.recommended_next_action=$("next-action").value.trim();r.review_status=$("review-status").value;return r;}
function buildSubmission(){const tier=$("tier-promotion").value||null;const rubric={};$("rubric-scores").querySelectorAll("[data-rubric]").forEach(i=>{rubric[i.dataset.rubric]=Number(i.value);});return{schema_version:"0.1",unit_id:currentReport.unit_id,item_id:tier?`${currentReport.unit_id}_${tier}`:null,reviewer_id:$("reviewer-id").value.trim(),review_date:$("review-date").value,tier_promotion:tier,review_status:$("review-status").value,rubric_scores:rubric,dimension_reviews:{statement_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null},context_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null},notation_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null},dependency_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null}},list_fields_accurate:false,recommended_next_action_accurate:true,corrected_report_path:null,corrected_report:readCorrected(),notes:$("review-notes").value.trim()};}
function preview(){if(currentReport)$("review-json").textContent=JSON.stringify(buildSubmission(),null,2);}
async function loadExample(){try{const m=await fetchJson(`${apiBase()}/examples/${$("example-select").value}`);currentReport=await fetchJson(`../../${m.artifacts.readiness_report}`);currentUnit=await fetchJson(`../../${m.artifacts.unit}`);correctedState=clone(currentReport);correctedState.review_status="human_reviewed";renderSource(currentUnit);renderDimensions();renderLists();renderRubric();$("review-date").value=new Date().toISOString().slice(0,10);$("review-status").value=$("tier-promotion").value==="gold"?"expert_reviewed":"human_reviewed";preview();$("load-status").textContent="Loaded.";}catch(e){$("load-status").textContent=String(e);}}
async function postJson(path,payload){const r=await fetch(`${apiBase()}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(JSON.stringify(b.detail||b));return b;}
$("load-example").onclick=loadExample;$("tier-promotion").onchange=()=>{$("review-status").value=$("tier-promotion").value==="gold"?"expert_reviewed":"human_reviewed";preview();};
["review-status","reviewer-id","review-notes","next-action"].forEach(id=>$(id).oninput=preview);$("dimension-grid").oninput=preview;$("list-fields").oninput=preview;$("rubric-scores").oninput=preview;
$("validate-review").onclick=async()=>{try{$("validation-result").textContent=JSON.stringify(await postJson("/validate/review-submission",buildSubmission()),null,2);}catch(e){$("validation-result").textContent=String(e);}};
$("submit-review").onclick=async()=>{try{$("validation-result").textContent=JSON.stringify(await postJson("/review/submit",buildSubmission()),null,2);}catch(e){$("validation-result").textContent=String(e);}};
loadExample();
