const DIMENSIONS=["statement_readiness","context_readiness","notation_readiness","dependency_readiness"];
const LIST_FIELDS=[["existing_theorem_candidates","Existing theorem candidates"],["constructive_path","Constructive path"],["blockers","Blockers"]];
const RUBRIC=[["source_fidelity","Source fidelity"],["actionability","Actionability"],["library_alignment","Library alignment"],["blocker_specificity","Blocker specificity"],["path_clarity","Path clarity"]];
let currentReport=null,currentUnit=null,correctedState=null;
const $=id=>document.getElementById(id);
const apiBase=()=>$("api-base").value.replace(/\/$/,"");
const linesToList=v=>v.split("\n").map(s=>s.trim()).filter(Boolean);
const listToLines=v=>(v||[]).join("\n");
const clone=o=>JSON.parse(JSON.stringify(o));
async function fetchJson(path){const r=await fetch(path);if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json();}
function renderSource(unit){$("source-spans").innerHTML=`<dl class="source-dl"><dt>Unit</dt><dd>${unit.unit_id}</dd><dt>Statement span</dt><dd>${unit.statement_span?`[${unit.statement_span.start}, ${unit.statement_span.end})`:"(none)"}</dd><dt>Proof span</dt><dd>${unit.proof_span?`[${unit.proof_span.start}, ${unit.proof_span.end})`:"(none)"}</dd><dt>Statement</dt><dd>${unit.statement}</dd><dt>Proof</dt><dd>${unit.proof||"(none)"}</dd></dl>`;}
function renderDimensions(){$("dimension-grid").innerHTML=DIMENSIONS.map(n=>{const c=currentReport[n],e=correctedState[n];return `<article class="dimension-card" data-dimension="${n}"><h3>${n}</h3><div class="side-by-side"><div><h4>Candidate</h4><p>${c.status}</p><pre>${listToLines(c.recovered)}</pre><pre>${listToLines(c.unresolved)}</pre></div><div><h4>Corrected</h4><input class="dim-status" value="${e.status}"/><textarea class="dim-recovered">${listToLines(e.recovered)}</textarea><textarea class="dim-unresolved">${listToLines(e.unresolved)}</textarea><textarea class="dim-notes">${e.notes||""}</textarea></div></div></article>`;}).join("");}
function renderLists(){$("list-fields").innerHTML=LIST_FIELDS.map(([k,l])=>`<div class="list-field" data-field="${k}"><h3>${l}</h3><div class="side-by-side"><pre>${listToLines(currentReport[k])}</pre><textarea class="corrected-list">${listToLines(correctedState[k])}</textarea></div></div>`).join("");$("next-action").value=correctedState.recommended_next_action;}
function renderRubric(){$("rubric-scores").innerHTML=RUBRIC.map(([k,l])=>`<label class="rubric-row"><span>${l}</span><input type="number" min="1" max="5" data-rubric="${k}" value="4"/></label>`).join("");}
function readCorrected(){const r=clone(correctedState);for(const n of DIMENSIONS){const card=$("dimension-grid").querySelector(`[data-dimension="${n}"]`);r[n]={status:card.querySelector(".dim-status").value.trim(),recovered:linesToList(card.querySelector(".dim-recovered").value),unresolved:linesToList(card.querySelector(".dim-unresolved").value),notes:card.querySelector(".dim-notes").value.trim()||null};}
for(const [k] of LIST_FIELDS){r[k]=linesToList($("list-fields").querySelector(`[data-field="${k}"] .corrected-list`).value);}r.recommended_next_action=$("next-action").value.trim();r.review_status=$("review-status").value;return r;}
function buildSubmission(){const tier=$("tier-promotion").value||null;const rubric={};$("rubric-scores").querySelectorAll("[data-rubric]").forEach(i=>{rubric[i.dataset.rubric]=Number(i.value);});return{schema_version:"0.1",unit_id:currentReport.unit_id,item_id:tier?`${currentReport.unit_id}_${tier}`:null,reviewer_id:$("reviewer-id").value.trim(),review_date:$("review-date").value,tier_promotion:tier,review_status:$("review-status").value,rubric_scores:rubric,dimension_reviews:{statement_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null},context_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null},notation_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null},dependency_readiness:{status_accurate:true,recovered_accurate:true,unresolved_accurate:true,notes:null}},list_fields_accurate:false,recommended_next_action_accurate:true,corrected_report_path:null,corrected_report:readCorrected(),notes:$("review-notes").value.trim()};}
function preview(){if(currentReport)$("review-json").textContent=JSON.stringify(buildSubmission(),null,2);}
async function loadExample(){try{const m=await fetchJson(`${apiBase()}/examples/${$("example-select").value}`);currentReport=await fetchJson(`../../${m.artifacts.readiness_report}`);currentUnit=await fetchJson(`../../${m.artifacts.unit}`);correctedState=clone(currentReport);correctedState.review_status="human_reviewed";renderSource(currentUnit);renderDimensions();renderLists();renderRubric();$("review-date").value=new Date().toISOString().slice(0,10);$("review-status").value=$("tier-promotion").value==="gold"?"expert_reviewed":"human_reviewed";preview();$("load-status").textContent="Loaded.";}catch(e){$("load-status").textContent=String(e);}}
async function postJson(path,payload){const r=await fetch(`${apiBase()}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(JSON.stringify(b.detail||b));return b;}
$("load-example").onclick=loadExample;$("tier-promotion").onchange=()=>{$("review-status").value=$("tier-promotion").value==="gold"?"expert_reviewed":"human_reviewed";preview();};
["review-status","reviewer-id","review-notes","next-action"].forEach(id=>$(id).oninput=preview);$("dimension-grid").oninput=preview;$("list-fields").oninput=preview;$("rubric-scores").oninput=preview;
$("validate-review").onclick=async()=>{try{$("validation-result").textContent=JSON.stringify(await postJson("/validate/review-submission",buildSubmission()),null,2);}catch(e){$("validation-result").textContent=String(e);}};
$("submit-review").onclick=async()=>{try{$("validation-result").textContent=JSON.stringify(await postJson("/review/submit",buildSubmission()),null,2);}catch(e){$("validation-result").textContent=String(e);}};
loadExample();
